### ISSUE TITLE
Depth logic

### ISSUE THREAD

**Issue by rayrutjes** [radiovisual/metalsmith-rootpath#5]
I totally see why this plugin can be useful, but it seems I am missing something in the implementation.

All my urls are like: http://example/{page-title}/
And I have of course the index on: http://example/

I am using a page template containing: <link rel="stylesheet" href="{{ rootPath }}css/app.css">
The rootPath is only correct on the index page. On all the others we miss one `../` because metalsmith puts every compiled page into its own directory.

Could you enlighten me on what is going wrong?

**Comment by rayrutjes** [comment]
Everything works as expected if I replace:

``` js
var levels = needles(file, pathslash);
```

with

``` js
var levels = needles(file, pathslash) + 1;
```

**Comment by radiovisual** [comment]
Is your compiled (built) directory structure identical to your source directory? If anything on your metalsmith build routine (plugins, tasks, etc) changes the output directory, then it breaks the relative relationship that rootPath tries to calculate. 

If you are 100% certain that your output directory matches the same directory structure as your source directory, then we may need to look a little deeper. 

**UPDATE**: The reason this happens, is because metalsmith-rootpath calculates the rootPath and attaches it to each file's metadata **before** the build process happens, so if anything on your build routine moves any files around, then the relative path is now broken.

**Comment by rayrutjes** [comment]
Whaou, thx for the prompt answer!
Here is my src dir:
![image](https://cloud.githubusercontent.com/assets/5570853/15807289/82247bac-2b5a-11e6-8c06-d83810f00ca7.png)
Resulting in:
![image](https://cloud.githubusercontent.com/assets/5570853/15807292/9beecaba-2b5a-11e6-8442-443d033845bb.png)

So for example my `cron` page is available at http://localhost:8080/cron/ but that page has an empty rootPath.

Here is my build script:

``` js
var Metalsmith  = require('metalsmith');
var sass        = require('metalsmith-sass');
var markdown    = require('metalsmith-markdown');
var layouts     = require('metalsmith-layouts');
var permalinks  = require('metalsmith-permalinks');
var rootPath    = require('metalsmith-rootpath');
var serve       = require('metalsmith-serve');
var watch       = require('metalsmith-watch');
var metallic    = require('metalsmith-metallic');
var sitemap     = require('metalsmith-mapsite');
var asset       = require('metalsmith-static');

var sassPaths = [
    'node_modules/foundation-sites/scss'
];

var siteBuild = Metalsmith(__dirname)
    // Allow for relative url generation.

    .source('./src')
    .destination('./build')


    // Compile sass files.
    .use(sass({
        includePaths: sassPaths,
        outputDir: 'css/'
    }))

    // Copy vendor assets to the build.
    .use(asset({
        src: './node_modules/jquery/dist',
        dest: './vendor/jquery'
    }))
    .use(asset({
        src: './node_modules/foundation-sites/dist',
        dest: './vendor/foundation-sites'
    }))

    // Add Highlight.js for code snippets.
    .use(metallic())

    // Parse Markdown.
    .use(markdown())

    .use(rootPath())

    .use(permalinks({
        pattern: ':title',
        relative: false
    }))

    .use(layouts({
        engine: 'handlebars'
    }))

    // Generate a sitemap.xml.
    .use(sitemap('xxx'));

if (process.env.NODE_ENV !== 'production') {
    siteBuild

    // Serve on localhost:8080.
    .use(serve())

    // Watch for changes.
    .use(
        watch({
            paths: {
                "${source}/**/*.md": true,
                "${source}/sass/**/*.scss": "sass/app.scss", 
                "layouts/**/*.html": "**/*.md"
            },
            livereload: true,
        })
    );
}

// Display errors.
siteBuild.build(function(err, files) {
    if (err) { throw err; }
});

```

**Comment by rayrutjes** [comment]
I just saw your update. I realize that the `permalink` plugin is conflicting. Maybe you could add a note about that conflict into your readme. Thank you for the quick reaction time! 🚀 .

**Comment by radiovisual** [comment]
Yeah, I can see what is happening, I will use the `cron.md` file in my example. At the time that the rootPath value was assigned to the `cron.md` file, the rootPath **was** `../`, but your build routine created a file `cron/index.html` that didn't exist when the rootPath value was being assigned to `cron.md`, so there are two reasons why it isn't working for you:
1. The `cron/index.html` didn't exist at compilation time, so it was never able to recieve a rootPath variable:
2. The rootPath for `cron.md`doesn't help you, because the `cron.md` file doesn't exist in your output, so it doesn't need a rootPath value

I believe it's the permalinks plugin that is changing your directory structure for you. If you want metalsmith-rootpath to work for you, you could try creating the structure you know you want in our src directory (create `cron/index.md` yourself), and have your markdown plugin render the `.md` to `.html` for you, that way you can get the output you want, still use relative paths with metalsmith-rootpath and still use the markdown plugin.

**Comment by radiovisual** [comment]
I have a note on my README warning people that metalsmith-rootpath requires identical source to output directories, and that anything that would change the directory structure during build-time will break the relative relationship (this includes plugins like permalinks).

**Comment by rayrutjes** [comment]
Actually it works, just have to put your plugin call after the permalink one!!!

**Comment by radiovisual** [comment]
Oh, nice catch! 👍 

I have some ideas to make this plugin a bit more flexible in the future, but for now it has served my needs to maintain an easy relative navigation / file structure in metalsmith.

**Comment by radiovisual** [comment]
@rayrutjes, if you have confirmed that you are getting a valid rootPath value on the files that have been generated/changed/moved by permalinks, then you have actually helped me realize a bit of metalsmith-rootpath's flexibility. If it works for you, then I can remove the warning on my README, and simply mention that metalsmith-rootpath must be run after any plugins or build routines that change the directory structure.

**Comment by rayrutjes** [comment]
@radiovisual I have just tested a lot of different scenarios, and it works like a charm! You should definitely update the readme in the way you suggested!

**Comment by radiovisual** [comment]
ok, awesome! Thanks for bringing that to my attention!

**Comment by radiovisual** [comment]
I added a unit test using metalsmith-permalinks to confirm this behavior. It's always nice to discover new flexibilities in your own plugins. 😄  👍

**Comment by rayrutjes** [comment]
Nice, your readme is much cleaner now!
